/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Shondesh;

import javax.swing.JFileChooser;
import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Download extends javax.swing.JFrame {
    
    /*decalre variable*/
    boolean comboRecent = false;
    String rootUrl = null;
    String userDate = null;
    MakeUrlListDataFile muldf = null;
    
    /*********************** showing combo data for this year ************************/
    private void showThisComboData(int maxDay){
        FindToday fd = new FindToday();
        int maxMonth = Integer.parseInt(fd.thisMonth());
        int maxYear = Integer.parseInt(fd.thisYear());
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        for(int I=1; I<=maxDay; I++)
            jComboBox1.addItem(String.valueOf(I));
        for(int I=1; I<=maxMonth; I++)
            jComboBox2.addItem(String.valueOf(I));
        for(int I=2006; I<=maxYear; I++)
            jComboBox3.addItem(String.valueOf(I));
    }
    
    /***********************showing initial data of combo 1,2,3**************************/
    private void showInitialComboData(){
        FindToday fd = new FindToday();
        showThisComboData(Integer.parseInt(fd.thisDate()));
        jComboBox1.setSelectedItem(fd.thisDate());
        jComboBox2.setSelectedItem(fd.thisMonth());
        jComboBox3.setSelectedItem(fd.thisYear());
    }
    
    /**************************showing recent data of combo 1,2,3****************************/
    private void showRecentComboData(){
        FindToday fd = new FindToday();
        String day = null;
        String month = null;
        String year = null;
        int userMonth = 0;
        int userYear = 0;
        try{
            day = jComboBox1.getSelectedItem().toString();
            month = jComboBox2.getSelectedItem().toString();
            year = jComboBox3.getSelectedItem().toString();
            userMonth = Integer.parseInt(month);
            userYear = Integer.parseInt(year);
        }catch(NullPointerException npe){
            return;
        }
        
        //checking with system date for finding this year & month
        int systemMonth = Integer.parseInt(fd.thisMonth());
        int systemYear = Integer.parseInt(fd.thisYear());
        System.out.println(userMonth+" "+"_"+userYear+" "+systemYear);
        if( userYear==systemYear ){
            int maxDay = 0;
            //if this year & month
            if( userMonth==systemMonth )
                maxDay = Integer.parseInt(fd.thisDate());
            else
                maxDay = fd.maxDay(userMonth, userYear);
            showThisComboData(maxDay);
            jComboBox1.setSelectedItem(day);
            jComboBox2.setSelectedItem(month);
            jComboBox3.setSelectedItem(year);
            return;
        }
        
        //if not this year
        int maxDay = fd.maxDay(userMonth, userYear);    
        int maxMonth = 12;
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        for(int I=1; I<=maxDay; I++)
            jComboBox1.addItem(String.valueOf(I));
        for(int I=1; I<=maxMonth; I++)
            jComboBox2.addItem(String.valueOf(I));
        jComboBox1.setSelectedItem(day);
        jComboBox2.setSelectedItem(month);
        jComboBox3.setSelectedItem(year);
        //System.out.println(year+month+day);
    }
    
    /************************return the recent date which selected by user***********************/
    void getUserDate(){
        if( jComboBox1.getSelectedItem()!=null && jComboBox2.getSelectedItem()!=null && jComboBox3.getSelectedItem()!=null ){
            String year = jComboBox3.getSelectedItem().toString();
            String month = jComboBox2.getSelectedItem().toString();
            String day = jComboBox1.getSelectedItem().toString();
            if( month.length()==1 )
                month = "0"+month;
            if( day.length()==1 )
                day = "0"+day;
            userDate = year+"-"+month+"-"+day;
            System.out.println(userDate);
        }
        //return userDate;
    }
    
    /**
     * Creates new form Download
     */
    public Download() {
        initComponents();
        setLocationRelativeTo(null);
        showInitialComboData();
        comboRecent = true;
        jRadioButton1.setSelected(true);
        rootUrl = "http://www.prothom-alo.com/";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Download");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("SolaimanLipi", 0, 18));
        jRadioButton1.setText("প্রথম আলো");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("SolaimanLipi", 0, 18));
        jRadioButton2.setText("নয়া দিগন্ত");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Download");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Day:");

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Year:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Month:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(297, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jRadioButton1, jRadioButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addGap(13, 13, 13)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jRadioButton1, jRadioButton2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();

        //storing today's date from system in desired format
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String today = sdf.format(now);
        
        //checking for naya-diganta
        getUserDate();
        if( userDate.equals(today)==false && rootUrl.equals("http://www.dailynayadiganta.com/")==true ){
            JOptionPane.showMessageDialog(rootPane, "Required data is not available.\nPlease try later.");
            new Download().setVisible(true);
        }
        else{
            try{
                System.out.println("=> "+userDate);
                muldf = new MakeUrlListDataFile(rootUrl, userDate);
                //jProgressBar1.setValue(jProgressBar1.getValue() + (int)muldf.msul.progress );
                //new SearchPage().setVisible(true);
                System.out.println("************** DOWNLOAD ***************************");

            }
            catch(Exception ioe){
                JOptionPane.showMessageDialog(rootPane, "Required data is not available.\nPlease try later.");
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    rootUrl = "http://www.prothom-alo.com/";
}//GEN-LAST:event_jRadioButton1ActionPerformed

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    rootUrl = "http://www.dailynayadiganta.com/";
}//GEN-LAST:event_jRadioButton2ActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    System.out.println("closing download");
    new SearchPage().setVisible(true);
    this.dispose();
}//GEN-LAST:event_formWindowClosing

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
    if( comboRecent==true){
        System.out.println("YEAR");
        comboRecent = false;
        showRecentComboData();
        comboRecent = true;
    }
}//GEN-LAST:event_jComboBox3ActionPerformed

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    if( comboRecent==true){
        System.out.println("MONTH");
        comboRecent = false;
        showRecentComboData();
        comboRecent = true;
    }
}//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Download.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Download().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
