/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserDocument.java
 *
 * Created on Feb 28, 2012, 10:46:54 AM
 */
package Shondesh;

import javax.swing.*;
import java.io.*;

/**
 *
 * @author RATUL
 */
public class UserDocument extends javax.swing.JFrame {

    String path = "";
    int myFileNames[];  //contain names of files which is given by me in sequentially.
    
    /** Creates new form UserDocument */
    public UserDocument() {
        initComponents();
    }
    
    /**/
    void add(String destPath){
        JFileChooser jfc = new JFileChooser();
        jfc.setApproveButtonText("Add");
        jfc.setDialogTitle("Add (less than 50KB)");
        
        //file add button clicked.
        int ret = jfc.showDialog(jfc, null);
        if (ret == JFileChooser.APPROVE_OPTION) {
            //checking fileSize
            long fileSize = jfc.getSelectedFile().length(); //fileSize in Bytes
            System.out.println("= "+fileSize);
            if( fileSize > (1024*50) ){   //measuring in 50KB
                JOptionPane.showMessageDialog(rootPane, "File size is huge.\nPlease choose a file less than 50KB.", "Error", JOptionPane.ERROR_MESSAGE);
                add(destPath);
                this.dispose();
                return ;
            }
            
            try {
                FileDirectory fd = new FileDirectory();
                String text = fd.getFileString(jfc.getSelectedFile().getPath());
                //System.out.println(jfc.getSelectedFile().getName()+" -> "+text);
                fd.makeDirs(new File(destPath));
                int I = 0;
                String filePath = destPath + "\\" + String.valueOf(I);
                for( ; fd.isExist(new File(filePath+".head"))==true; I++){
                    System.out.println("=> "+filePath);
                    filePath = destPath + "\\" + String.valueOf(I);
                }
                fd.makeFileUtf(filePath+".head", jfc.getSelectedFile().getName());    //file name is saved as headline
                fd.makeFileUtf(filePath+".news", text);                               //file contents are saved as news
                
                //again call
                add(destPath);
            }
            catch (Exception ex) {
                //Logger.getLogger(SearchPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "File doesn't exist.\nPlease select a file.", "File not fuond !!", JOptionPane.ERROR_MESSAGE);
            }
        }
        this.dispose();
    }
    
    /**/
    void delete(String destPath){
        path = destPath;
        this.setTitle("Delete");
        this.setVisible(true);
        
        FileDirectory fd = new FileDirectory();
        int maxFile = fd.getDirectoryChildNumber(new File(destPath))/2;
        String realFileNames[] = new String[maxFile];
        myFileNames = new int[maxFile];
        
        int countFile = 0;
        for(int I=0; countFile<maxFile; I++){
            String myFileName = destPath + "\\" + String.valueOf(I) + ".head";
            try{
                realFileNames[countFile] = fd.getFileString(myFileName);
                myFileNames[countFile] = I;
                countFile++;
            }catch(IOException ioe){}
        }
        jList1.setListData(realFileNames);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setFont(new java.awt.Font("SolaimanLipi", 2, 12));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("SolaimanLipi", 0, 14));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("File Names :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Contents:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    int myFileName = myFileNames[jList1.getSelectedIndex()];
    FileDirectory fd = new FileDirectory();
    try{
        jTextArea1.setText(fd.getFileString(path+"\\"+String.valueOf(myFileName)+".news"));
    }catch(IOException ioe){}
}//GEN-LAST:event_jList1MouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int myFileName = myFileNames[jList1.getSelectedIndex()];
    FileDirectory fd = new FileDirectory();
    String filePath = path+"\\"+String.valueOf(myFileName);
    fd.deleteDir(new File(filePath+".head"));
    fd.deleteDir(new File(filePath+".news"));
    JOptionPane.showMessageDialog(rootPane, "           Deleted");
    delete(path);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UserDocument().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
